-- Migration: Populate all site texts from frontend LanguageContext
-- This migration inserts all translation keys from the frontend language context
-- into the site_texts table for both English (en) and Arabic (ar) languages.
-- 
-- Created: 2025-11-14
-- Purpose: Ensure all frontend translations are available in backend for management

-- English translations
INSERT INTO site_texts (key, language_code, value, type, namespace, context) VALUES
('home', 'en', 'Home', 'ui', 'navigation', 'Main navigation'),
('shop', 'en', 'Shop', 'ui', 'navigation', 'Main navigation'),
('stores', 'en', 'Stores', 'ui', 'navigation', 'Main navigation'),
('cart', 'en', 'Cart', 'ui', 'navigation', 'Main navigation'),
('account', 'en', 'Account', 'ui', 'navigation', 'Main navigation'),
('search', 'en', 'Search products...', 'ui', 'forms', 'Search input placeholder'),
('categories', 'en', 'Categories', 'ui', 'navigation', 'Category filter label'),
('featuredProducts', 'en', 'Featured Products', 'ui', 'products', 'Featured products section'),
('latest_products', 'en', 'Latest Products', 'ui', 'products', 'Latest products section'),
('best_products', 'en', 'Best products', 'ui', 'products', 'Best products section'),
('best_selling', 'en', 'Best selling', 'ui', 'products', 'Best selling filter'),
('discounts_20', 'en', '20% discounts', 'ui', 'products', 'Discount badge label'),
('showing_of_products', 'en', 'Showing {count} of {total} products', 'ui', 'products', 'Product pagination text'),
('allProducts', 'en', 'All Products', 'ui', 'products', 'All products section'),
('viewAll', 'en', 'View All', 'ui', 'buttons', 'View all button'),
('addToCart', 'en', 'Add to Cart', 'ui', 'buttons', 'Add to cart button'),
('buyNow', 'en', 'Buy Now', 'ui', 'buttons', 'Buy now button'),
('reviews', 'en', 'Reviews', 'ui', 'products', 'Reviews section'),
('writeReview', 'en', 'Write a Review', 'ui', 'buttons', 'Write review button'),
('checkout', 'en', 'Checkout', 'ui', 'navigation', 'Checkout page title'),
('subtotal', 'en', 'Subtotal', 'ui', 'cart', 'Cart subtotal label'),
('shipping', 'en', 'Shipping', 'ui', 'cart', 'Shipping cost label'),
('discount', 'en', 'Discount', 'ui', 'cart', 'Discount label'),
('total', 'en', 'Total', 'ui', 'cart', 'Total amount label'),
('applyCoupon', 'en', 'Apply Coupon', 'ui', 'buttons', 'Apply coupon button'),
('placeOrder', 'en', 'Place Order', 'ui', 'buttons', 'Place order button'),
('myOrders', 'en', 'My Orders', 'ui', 'account', 'My orders section'),
('addresses', 'en', 'Addresses', 'ui', 'account', 'Saved addresses section'),
('logout', 'en', 'Logout', 'ui', 'buttons', 'Logout button'),
('login', 'en', 'Login', 'ui', 'buttons', 'Login button'),
('register', 'en', 'Register', 'ui', 'buttons', 'Register button'),
('add_account', 'en', 'Add account', 'ui', 'account', 'Add account option'),
('manage_account_info', 'en', 'Manage your account info.', 'ui', 'account', 'Account management description'),
('profile', 'en', 'Profile', 'ui', 'account', 'Profile tab'),
('security', 'en', 'Security', 'ui', 'account', 'Security settings tab'),
('billing', 'en', 'Billing', 'ui', 'account', 'Billing tab'),
('profile_details', 'en', 'Profile details', 'ui', 'account', 'Profile details section'),
('full_name', 'en', 'Full name', 'ui', 'forms', 'Full name field label'),
('add_email', 'en', 'Add email address', 'ui', 'forms', 'Email field label'),
('password_label', 'en', 'Password', 'ui', 'forms', 'Password field label'),
('set_password', 'en', 'Set password', 'ui', 'forms', 'Set password button/link'),
('manage_billing', 'en', 'Manage your subscription and payment methods.', 'ui', 'account', 'Billing management description'),
('development_mode', 'en', 'Development mode', 'ui', 'admin', 'Development mode label'),
('inStock', 'en', 'In Stock', 'ui', 'products', 'Stock status'),
('outOfStock', 'en', 'Out of Stock', 'ui', 'products', 'Stock status'),
('price', 'en', 'Price', 'ui', 'products', 'Price label'),
('rating', 'en', 'Rating', 'ui', 'products', 'Rating label'),
('products', 'en', 'Products', 'ui', 'navigation', 'Products section'),
('footer_brand', 'en', 'gocart.', 'content', 'footer', 'Footer brand name'),
('footer_description', 'en', 'Welcome to gocart, your ultimate destination for the latest and smartest gadgets. From smartphones and smartwatches to essential accessories, we bring you the best in innovation — all in one place.', 'content', 'footer', 'Footer company description'),
('footer_contact_phone', 'en', '+1-212-456-7890', 'content', 'footer', 'Footer contact phone'),
('footer_contact_email', 'en', 'contact@example.com', 'content', 'footer', 'Footer contact email'),
('footer_contact_address', 'en', '794 Francisco, 94102', 'content', 'footer', 'Footer contact address'),
('create_store', 'en', 'Create Your Store', 'ui', 'buttons', 'Create store button'),
('product_earphones', 'en', 'Earphones', 'ui', 'products', 'Product category'),
('product_headphones', 'en', 'Headphones', 'ui', 'products', 'Product category'),
('product_smartphones', 'en', 'Smartphones', 'ui', 'products', 'Product category'),
('product_laptops', 'en', 'Laptops', 'ui', 'products', 'Product category'),
('become_seller', 'en', 'Become a Seller', 'ui', 'buttons', 'Become seller CTA'),
('seller_dashboard', 'en', 'Seller Dashboard', 'ui', 'navigation', 'Seller dashboard title'),
('admin_dashboard', 'en', 'Admin Dashboard', 'ui', 'navigation', 'Admin dashboard title'),
('manage_profile', 'en', 'Manage Profile', 'ui', 'account', 'Manage profile option'),
('my_orders', 'en', 'My Orders', 'ui', 'account', 'My orders navigation'),
('website', 'en', 'Website', 'ui', 'footer', 'Website section in footer'),
('privacy_policy', 'en', 'Privacy Policy', 'ui', 'footer', 'Privacy policy link'),
('become_plus_member', 'en', 'Become Plus Member', 'ui', 'buttons', 'Membership CTA'),
('contact', 'en', 'Contact', 'ui', 'footer', 'Contact section in footer'),
('our_specifications', 'en', 'Our Specifications', 'ui', 'content', 'Specifications section title'),
('spec_free_shipping_title', 'en', 'Free Shipping', 'ui', 'features', 'Feature title'),
('spec_free_shipping_desc', 'en', 'Enjoy fast, free delivery on every order no conditions, just reliable doorstep.', 'ui', 'features', 'Feature description'),
('spec_easy_return_title', 'en', '7 Days easy Return', 'ui', 'features', 'Feature title'),
('spec_easy_return_desc', 'en', 'Change your mind? No worries. Return any item within 7 days.', 'ui', 'features', 'Feature description'),
('spec_support_title', 'en', '24/7 Customer Support', 'ui', 'features', 'Feature title'),
('spec_support_desc', 'en', 'We''re here for you. Get expert help with our customer support.', 'ui', 'features', 'Feature description'),
('seller_dashboard_title', 'en', 'Seller Dashboard', 'ui', 'seller', 'Seller dashboard page title'),
('dashboard_stats_total_products', 'en', 'Total Products', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_earnings', 'en', 'Total Earnings', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_orders', 'en', 'Total Orders', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_ratings', 'en', 'Total Ratings', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_reviews', 'en', 'Total Reviews', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_recent_orders_title', 'en', 'Recent Orders', 'ui', 'dashboard', 'Dashboard section title'),
('dashboard_recent_orders_empty', 'en', 'No orders yet. Start selling to see orders here', 'ui', 'dashboard', 'Empty state message'),
('dashboard_quick_stats_title', 'en', 'Quick Stats', 'ui', 'dashboard', 'Dashboard section title'),
('dashboard_quick_stats_conversion_rate', 'en', 'Conversion Rate', 'ui', 'dashboard', 'Quick stats metric'),
('dashboard_quick_stats_avg_order_value', 'en', 'Avg Order Value', 'ui', 'dashboard', 'Quick stats metric'),
('dashboard_quick_stats_customer_satisfaction', 'en', 'Customer Satisfaction', 'ui', 'dashboard', 'Quick stats metric'),
('header_brand', 'en', 'gocart', 'ui', 'header', 'Brand name in header'),
('header_store_label', 'en', 'Store:', 'ui', 'header', 'Store label'),
('add_product', 'en', 'Add Product', 'ui', 'seller', 'Add product button/link'),
('manage_products', 'en', 'Manage Products', 'ui', 'seller', 'Manage products button/link'),
('dashboard', 'en', 'Dashboard', 'ui', 'seller', 'Dashboard link/button'),
('store_orders', 'en', 'Store Orders', 'ui', 'orders', 'Seller view orders title'),
('no_orders_yet', 'en', 'No Orders Yet', 'ui', 'orders', 'Empty state heading'),
('no_orders_empty_customer', 'en', 'Start shopping to create your first order', 'ui', 'orders', 'Empty state message'),
('no_orders_empty_seller', 'en', 'Orders will appear here once customers start purchasing', 'ui', 'orders', 'Empty state message'),
('no_orders', 'en', 'No orders yet', 'ui', 'orders', 'Empty state text'),
('order_number', 'en', 'Order #', 'ui', 'orders', 'Order ID label'),
('order_details', 'en', 'Order Details', 'ui', 'orders', 'Modal title'),
('order_id', 'en', 'Order ID', 'ui', 'orders', 'Label'),
('order_date', 'en', 'Order Date', 'ui', 'orders', 'Label'),
('order_status', 'en', 'Order Status', 'ui', 'orders', 'Label'),
('order_placed', 'en', 'Order Placed', 'ui', 'orders', 'Status timeline'),
('order_summary', 'en', 'Order Summary', 'ui', 'orders', 'Section title'),
('order_items', 'en', 'Order Items', 'ui', 'orders', 'Section title'),
('delivery_address', 'en', 'Delivery Address', 'ui', 'orders', 'Section title'),
('payment_information', 'en', 'Payment Information', 'ui', 'orders', 'Section title'),
('order_notes', 'en', 'Order Notes', 'ui', 'orders', 'Section title'),
('payment_method', 'en', 'Method', 'ui', 'orders', 'Payment method label'),
('in_transit', 'en', 'In Transit', 'ui', 'orders', 'Status'),
('delivered_text', 'en', 'Delivered', 'ui', 'orders', 'Status'),
('your_package_delivered', 'en', 'Your package has been delivered', 'ui', 'orders', 'Status message'),
('your_package_on_way', 'en', 'Your package is on its way', 'ui', 'orders', 'Status message'),
('payment_status_label', 'en', 'Payment: ', 'ui', 'orders', 'Badge prefix'),
('qty_label', 'en', 'Qty:', 'ui', 'orders', 'Quantity label'),
('store_label_orders', 'en', 'Store:', 'ui', 'orders', 'Store label'),
('orders_count', 'en', '{count} Orders', 'ui', 'orders', 'Title with count'),
('close_button', 'en', 'Close', 'ui', 'buttons', 'Close button'),
('admin_dashboard_title', 'en', 'Admin Dashboard', 'ui', 'admin', 'Admin dashboard page title'),
('admin_total_products', 'en', 'Total Products', 'ui', 'admin', 'Admin stats card'),
('admin_total_revenue', 'en', 'Total Revenue', 'ui', 'admin', 'Admin stats card'),
('admin_total_orders', 'en', 'Total Orders', 'ui', 'admin', 'Admin stats card'),
('admin_total_stores', 'en', 'Total Stores', 'ui', 'admin', 'Admin stats card'),
('admin_orders_per_day', 'en', 'Orders / Day', 'ui', 'admin', 'Admin chart title'),
('admin_nav_dashboard', 'en', 'Dashboard', 'ui', 'admin', 'Navigation item'),
('admin_nav_stores', 'en', 'Stores', 'ui', 'admin', 'Navigation item'),
('admin_nav_applications', 'en', 'Seller Applications', 'ui', 'admin', 'Navigation item'),
('admin_nav_coupons', 'en', 'Coupons', 'ui', 'admin', 'Navigation item'),
('admin_nav_translations', 'en', 'Translations', 'ui', 'admin', 'Navigation item'),
('admin_greeting', 'en', 'Hi, {name}', 'ui', 'admin', 'Greeting message')
ON CONFLICT (key, language_code) DO UPDATE SET
  value = EXCLUDED.value,
  type = EXCLUDED.type,
  namespace = EXCLUDED.namespace,
  context = EXCLUDED.context,
  updated_at = now();

-- Arabic translations
INSERT INTO site_texts (key, language_code, value, type, namespace, context) VALUES
('home', 'ar', 'الرئيسية', 'ui', 'navigation', 'Main navigation'),
('shop', 'ar', 'تسوق', 'ui', 'navigation', 'Main navigation'),
('stores', 'ar', 'المتاجر', 'ui', 'navigation', 'Main navigation'),
('cart', 'ar', 'السلة', 'ui', 'navigation', 'Main navigation'),
('account', 'ar', 'الحساب', 'ui', 'navigation', 'Main navigation'),
('search', 'ar', 'ابحث عن المنتجات...', 'ui', 'forms', 'Search input placeholder'),
('categories', 'ar', 'الفئات', 'ui', 'navigation', 'Category filter label'),
('featuredProducts', 'ar', 'المنتجات المميزة', 'ui', 'products', 'Featured products section'),
('latest_products', 'ar', 'أحدث المنتجات', 'ui', 'products', 'Latest products section'),
('best_products', 'ar', 'أفضل المنتجات', 'ui', 'products', 'Best products section'),
('best_selling', 'ar', 'الأكثر مبيعًا', 'ui', 'products', 'Best selling filter'),
('discounts_20', 'ar', 'خصومات 20%', 'ui', 'products', 'Discount badge label'),
('showing_of_products', 'ar', 'عرض {count} من {total} منتج', 'ui', 'products', 'Product pagination text'),
('allProducts', 'ar', 'جميع المنتجات', 'ui', 'products', 'All products section'),
('viewAll', 'ar', 'عرض الكل', 'ui', 'buttons', 'View all button'),
('addToCart', 'ar', 'أضف إلى السلة', 'ui', 'buttons', 'Add to cart button'),
('buyNow', 'ar', 'اشتر الآن', 'ui', 'buttons', 'Buy now button'),
('reviews', 'ar', 'التقييمات', 'ui', 'products', 'Reviews section'),
('writeReview', 'ar', 'اكتب تقييم', 'ui', 'buttons', 'Write review button'),
('checkout', 'ar', 'إتمام الطلب', 'ui', 'navigation', 'Checkout page title'),
('subtotal', 'ar', 'المجموع الفرعي', 'ui', 'cart', 'Cart subtotal label'),
('shipping', 'ar', 'الشحن', 'ui', 'cart', 'Shipping cost label'),
('discount', 'ar', 'الخصم', 'ui', 'cart', 'Discount label'),
('total', 'ar', 'الإجمالي', 'ui', 'cart', 'Total amount label'),
('applyCoupon', 'ar', 'تطبيق القسيمة', 'ui', 'buttons', 'Apply coupon button'),
('placeOrder', 'ar', 'تأكيد الطلب', 'ui', 'buttons', 'Place order button'),
('myOrders', 'ar', 'طلباتي', 'ui', 'account', 'My orders section'),
('addresses', 'ar', 'العناوين', 'ui', 'account', 'Saved addresses section'),
('logout', 'ar', 'تسجيل الخروج', 'ui', 'buttons', 'Logout button'),
('login', 'ar', 'تسجيل الدخول', 'ui', 'buttons', 'Login button'),
('register', 'ar', 'إنشاء حساب', 'ui', 'buttons', 'Register button'),
('add_account', 'ar', 'إضافة حساب', 'ui', 'account', 'Add account option'),
('manage_account_info', 'ar', 'إدارة معلومات حسابك.', 'ui', 'account', 'Account management description'),
('profile', 'ar', 'الملف الشخصي', 'ui', 'account', 'Profile tab'),
('security', 'ar', 'الأمان', 'ui', 'account', 'Security settings tab'),
('billing', 'ar', 'الفواتير', 'ui', 'account', 'Billing tab'),
('profile_details', 'ar', 'تفاصيل الملف', 'ui', 'account', 'Profile details section'),
('full_name', 'ar', 'الاسم الكامل', 'ui', 'forms', 'Full name field label'),
('add_email', 'ar', 'إضافة عنوان بريد إلكتروني', 'ui', 'forms', 'Email field label'),
('password_label', 'ar', 'كلمة المرور', 'ui', 'forms', 'Password field label'),
('set_password', 'ar', 'تعيين كلمة مرور', 'ui', 'forms', 'Set password button/link'),
('manage_billing', 'ar', 'إدارة اشتراكك وطريقة الدفع.', 'ui', 'account', 'Billing management description'),
('development_mode', 'ar', 'وضع التطوير', 'ui', 'admin', 'Development mode label'),
('inStock', 'ar', 'متوفر', 'ui', 'products', 'Stock status'),
('outOfStock', 'ar', 'غير متوفر', 'ui', 'products', 'Stock status'),
('price', 'ar', 'السعر', 'ui', 'products', 'Price label'),
('rating', 'ar', 'التقييم', 'ui', 'products', 'Rating label'),
('products', 'ar', 'المنتجات', 'ui', 'navigation', 'Products section'),
('footer_brand', 'ar', 'gocart.', 'content', 'footer', 'Footer brand name'),
('footer_description', 'ar', 'مرحبًا بك في gocart، وجهتك المفضلة لأحدث وأذكى الأدوات. من الهواتف الذكية والساعات الذكية إلى الملحقات الأساسية، نقدم لك الأفضل في الابتكار — كل ذلك في مكان واحد.', 'content', 'footer', 'Footer company description'),
('footer_contact_phone', 'ar', '+1-212-456-7890', 'content', 'footer', 'Footer contact phone'),
('footer_contact_email', 'ar', 'contact@example.com', 'content', 'footer', 'Footer contact email'),
('footer_contact_address', 'ar', '794 Francisco, 94102', 'content', 'footer', 'Footer contact address'),
('create_store', 'ar', 'إنشاء متجرك', 'ui', 'buttons', 'Create store button'),
('product_earphones', 'ar', 'سماعات أذن', 'ui', 'products', 'Product category'),
('product_headphones', 'ar', 'سماعات رأس', 'ui', 'products', 'Product category'),
('product_smartphones', 'ar', 'هواتف ذكية', 'ui', 'products', 'Product category'),
('product_laptops', 'ar', 'أجهزة كمبيوتر محمولة', 'ui', 'products', 'Product category'),
('become_seller', 'ar', 'التسجيل كبائع', 'ui', 'buttons', 'Become seller CTA'),
('seller_dashboard', 'ar', 'لوحة البائع', 'ui', 'navigation', 'Seller dashboard title'),
('admin_dashboard', 'ar', 'لوحة المشرف', 'ui', 'navigation', 'Admin dashboard title'),
('manage_profile', 'ar', 'إدارة الملف', 'ui', 'account', 'Manage profile option'),
('my_orders', 'ar', 'طلباتي', 'ui', 'account', 'My orders navigation'),
('website', 'ar', 'الموقع', 'ui', 'footer', 'Website section in footer'),
('privacy_policy', 'ar', 'سياسة الخصوصية', 'ui', 'footer', 'Privacy policy link'),
('become_plus_member', 'ar', 'انضم كعضو بلس', 'ui', 'buttons', 'Membership CTA'),
('contact', 'ar', 'اتصل بنا', 'ui', 'footer', 'Contact section in footer'),
('our_specifications', 'ar', 'مواصفاتنا', 'ui', 'content', 'Specifications section title'),
('spec_free_shipping_title', 'ar', 'شحن مجاني', 'ui', 'features', 'Feature title'),
('spec_free_shipping_desc', 'ar', 'استمتع بتوصيل سريع ومجاني على كل طلب دون شروط، فقط توصيل موثوق إلى عتبة دارك.', 'ui', 'features', 'Feature description'),
('spec_easy_return_title', 'ar', 'إرجاع سهل خلال 7 أيام', 'ui', 'features', 'Feature title'),
('spec_easy_return_desc', 'ar', 'غيرت رأيك؟ لا مشكلة. أعد أي سلعة خلال 7 أيام.', 'ui', 'features', 'Feature description'),
('spec_support_title', 'ar', 'دعم العملاء 24/7', 'ui', 'features', 'Feature title'),
('spec_support_desc', 'ar', 'نحن هنا من أجلك. احصل على مساعدة خبراء من دعم العملاء لدينا.', 'ui', 'features', 'Feature description'),
('seller_dashboard_title', 'ar', 'لوحة البائع', 'ui', 'seller', 'Seller dashboard page title'),
('dashboard_stats_total_products', 'ar', 'إجمالي المنتجات', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_earnings', 'ar', 'إجمالي الأرباح', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_orders', 'ar', 'إجمالي الطلبات', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_ratings', 'ar', 'إجمالي التقييمات', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_stats_total_reviews', 'ar', 'إجمالي المراجعات', 'ui', 'dashboard', 'Dashboard stats card'),
('dashboard_recent_orders_title', 'ar', 'الطلبات الأخيرة', 'ui', 'dashboard', 'Dashboard section title'),
('dashboard_recent_orders_empty', 'ar', 'لا توجد طلبات حتى الآن. ابدأ البيع لترى الطلبات هنا', 'ui', 'dashboard', 'Empty state message'),
('dashboard_quick_stats_title', 'ar', 'الإحصائيات السريعة', 'ui', 'dashboard', 'Dashboard section title'),
('dashboard_quick_stats_conversion_rate', 'ar', 'معدل التحويل', 'ui', 'dashboard', 'Quick stats metric'),
('dashboard_quick_stats_avg_order_value', 'ar', 'متوسط قيمة الطلب', 'ui', 'dashboard', 'Quick stats metric'),
('dashboard_quick_stats_customer_satisfaction', 'ar', 'رضا العملاء', 'ui', 'dashboard', 'Quick stats metric'),
('header_brand', 'ar', 'gocart', 'ui', 'header', 'Brand name in header'),
('header_store_label', 'ar', 'المتجر:', 'ui', 'header', 'Store label'),
('add_product', 'ar', 'إضافة منتج', 'ui', 'seller', 'Add product button/link'),
('manage_products', 'ar', 'إدارة المنتجات', 'ui', 'seller', 'Manage products button/link'),
('dashboard', 'ar', 'لوحة التحكم', 'ui', 'seller', 'Dashboard link/button'),
('store_orders', 'ar', 'طلبات المتجر', 'ui', 'orders', 'Seller view orders title'),
('no_orders_yet', 'ar', 'لا توجد طلبات حتى الآن', 'ui', 'orders', 'Empty state heading'),
('no_orders_empty_customer', 'ar', 'ابدأ التسوق لإنشاء طلبك الأول', 'ui', 'orders', 'Empty state message'),
('no_orders_empty_seller', 'ar', 'ستظهر الطلبات هنا بمجرد أن يبدأ العملاء الشراء', 'ui', 'orders', 'Empty state message'),
('no_orders', 'ar', 'لا توجد طلبات بعد', 'ui', 'orders', 'Empty state text'),
('order_number', 'ar', 'الطلب #', 'ui', 'orders', 'Order ID label'),
('order_details', 'ar', 'تفاصيل الطلب', 'ui', 'orders', 'Modal title'),
('order_id', 'ar', 'رقم الطلب', 'ui', 'orders', 'Label'),
('order_date', 'ar', 'تاريخ الطلب', 'ui', 'orders', 'Label'),
('order_status', 'ar', 'حالة الطلب', 'ui', 'orders', 'Label'),
('order_placed', 'ar', 'تم تأكيد الطلب', 'ui', 'orders', 'Status timeline'),
('order_summary', 'ar', 'ملخص الطلب', 'ui', 'orders', 'Section title'),
('order_items', 'ar', 'عناصر الطلب', 'ui', 'orders', 'Section title'),
('delivery_address', 'ar', 'عنوان التسليم', 'ui', 'orders', 'Section title'),
('payment_information', 'ar', 'معلومات الدفع', 'ui', 'orders', 'Section title'),
('order_notes', 'ar', 'ملاحظات الطلب', 'ui', 'orders', 'Section title'),
('payment_method', 'ar', 'الطريقة', 'ui', 'orders', 'Payment method label'),
('in_transit', 'ar', 'قيد الشحن', 'ui', 'orders', 'Status'),
('delivered_text', 'ar', 'تم التسليم', 'ui', 'orders', 'Status'),
('your_package_delivered', 'ar', 'تم تسليم حزمتك', 'ui', 'orders', 'Status message'),
('your_package_on_way', 'ar', 'حزمتك في الطريق إليك', 'ui', 'orders', 'Status message'),
('payment_status_label', 'ar', 'الدفع: ', 'ui', 'orders', 'Badge prefix'),
('qty_label', 'ar', 'الكمية:', 'ui', 'orders', 'Quantity label'),
('store_label_orders', 'ar', 'المتجر:', 'ui', 'orders', 'Store label'),
('orders_count', 'ar', '{count} طلب', 'ui', 'orders', 'Title with count'),
('close_button', 'ar', 'إغلاق', 'ui', 'buttons', 'Close button'),
('admin_dashboard_title', 'ar', 'لوحة المسؤول', 'ui', 'admin', 'Admin dashboard page title'),
('admin_total_products', 'ar', 'إجمالي المنتجات', 'ui', 'admin', 'Admin stats card'),
('admin_total_revenue', 'ar', 'إجمالي الإيرادات', 'ui', 'admin', 'Admin stats card'),
('admin_total_orders', 'ar', 'إجمالي الطلبات', 'ui', 'admin', 'Admin stats card'),
('admin_total_stores', 'ar', 'إجمالي المتاجر', 'ui', 'admin', 'Admin stats card'),
('admin_orders_per_day', 'ar', 'الطلبات / اليوم', 'ui', 'admin', 'Admin chart title'),
('admin_nav_dashboard', 'ar', 'لوحة التحكم', 'ui', 'admin', 'Navigation item'),
('admin_nav_stores', 'ar', 'المتاجر', 'ui', 'admin', 'Navigation item'),
('admin_nav_applications', 'ar', 'طلبات البائعين', 'ui', 'admin', 'Navigation item'),
('admin_nav_coupons', 'ar', 'الكوبونات', 'ui', 'admin', 'Navigation item'),
('admin_nav_translations', 'ar', 'الترجمات', 'ui', 'admin', 'Navigation item'),
('admin_greeting', 'ar', 'مرحبا، {name}', 'ui', 'admin', 'Greeting message')
ON CONFLICT (key, language_code) DO UPDATE SET
  value = EXCLUDED.value,
  type = EXCLUDED.type,
  namespace = EXCLUDED.namespace,
  context = EXCLUDED.context,
  updated_at = now();
