// This file is automatically generated by the Supabase CLI but
// we allow reading Vite env variables here so the runtime picks up
// values from your `.env` when available. If you regenerate this
// file from the Supabase tooling you may want to keep the env logic
// or re-apply it.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

// Prefer environment variables (Vite: import.meta.env) but fall back
// to the embedded values so existing behavior remains until you
// update your `.env` file.
const DEFAULT_SUPABASE_URL = "https://qlhpzsucftqcakiotgpc.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsaHB6c3VjZnRxY2FraW90Z3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MDgxMTUsImV4cCI6MjA3NzE4NDExNX0.Giemxio92FcpcPpMpJhc4CqKe8sQXRZWEFJqcWBUVeQ";

// Vite exposes env vars via import.meta.env. Typescript may complain
// about these fields if not declared; Vite's typing should cover
// them. We also support process.env as a fallback for other runtimes.
const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env?.VITE_SUPABASE_URL : undefined) || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env?.VITE_SUPABASE_PUBLISHABLE_KEY : undefined) || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Example import:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use localStorage by default for the browser client
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Temporarily expose supabase client to window for console testing.
// NOTE: temporary test exposure removed. Do NOT expose the supabase client on window in production.